/// Model dimension aligned to make-level context for rankings and drilldown analysis.
table DimModel
	column ModelKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ModelKey

	column MakeKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: MakeKey

	column MakeName
		dataType: string
		summarizeBy: none
		sourceColumn: MakeName

	column ModelName
		dataType: string
		summarizeBy: none
		sourceColumn: ModelName

	partition DimModel = m
		mode: import
		source =
			let
				Datafilepath = "C:\Users\User\Downloads\Norway"
				Source = Csv.Document(File.Contents(Datafilepath & "\norway_new_car_sales_by_model.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    TrimmedText = Table.TransformColumns(PromotedHeaders, {{"Make", each Text.Trim(_), type text}, {"Model", each Text.Trim(_), type text}}),
			    DistinctModels = Table.Distinct(Table.SelectColumns(TrimmedText, {"Make", "Model"})),
			    MakeLookup = Table.Distinct(Table.SelectColumns(TrimmedText, {"Make"})),
			    AddedMakeKey = Table.AddIndexColumn(MakeLookup, "MakeKey", 1, 1),
			    RenamedMake = Table.RenameColumns(AddedMakeKey, {{"Make", "MakeName"}}),
			    JoinedToMake = Table.NestedJoin(DistinctModels, {"Make"}, RenamedMake, {"MakeName"}, "MakeLookup", JoinKind.LeftOuter),
			    ExpandedMakeKey = Table.ExpandTableColumn(JoinedToMake, "MakeLookup", {"MakeKey"}, {"MakeKey"}),
			    AddedModelKey = Table.AddIndexColumn(ExpandedMakeKey, "ModelKey", 1, 1),
			    Final = Table.ReorderColumns(Table.RenameColumns(AddedModelKey, {{"Model", "ModelName"}, {"Make", "MakeName"}}), {"ModelKey", "MakeKey", "MakeName", "ModelName"})
			in
			    Final
