/// Trimmed make dimension used for top-ranking, filtering, and model-to-make navigation.
table DimMake
	column MakeKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: MakeKey

	column MakeName
		dataType: string
		summarizeBy: none
		sourceColumn: MakeName

	partition DimMake = m
		mode: import
		source =
			let
				Datafilepath = "C:\\Users\\User\\Desktop\\Agent\\PowerBiAgent\\Data"
				Source = Csv.Document(File.Contents(Datafilepath & "\\norway_new_car_sales_by_make.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    TrimmedText = Table.TransformColumns(PromotedHeaders, {{"Make", each Text.Trim(_), type text}}),
			    DistinctMakes = Table.Distinct(Table.SelectColumns(TrimmedText, {"Make"})),
			    AddedMakeKey = Table.AddIndexColumn(DistinctMakes, "MakeKey", 1, 1),
			    Final = Table.RenameColumns(AddedMakeKey, {{"Make", "MakeName"}})
			in
			    Final
