/// Monthly model-level sales totals and source percentages used for model rankings and make-to-model drilldowns.
table FactModelSales
	column DateKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: DateKey

	column Year
		dataType: int64
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		summarizeBy: none
		sourceColumn: Month

	column MakeKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: MakeKey

	column ModelKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ModelKey

	column MakeName
		dataType: string
		summarizeBy: none
		sourceColumn: Make

	column ModelName
		dataType: string
		summarizeBy: none
		sourceColumn: Model

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity

	column Pct
		dataType: double
		summarizeBy: average
		sourceColumn: Pct

	partition FactModelSales = m
		mode: import
		source =
			let
				Datafilepath = "C:\\Users\\User\\Desktop\\Agent\\PowerBiAgent\\Data",
				Source = Csv.Document(File.Contents(Datafilepath & "\\norway_new_car_sales_by_model.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(PromotedHeaders, {{"Year", Int64.Type}, {"Month", Int64.Type}, {"Make", type text}, {"Model", type text}, {"Quantity", Int64.Type}, {"Pct", type number}}),
				Trimmed = Table.TransformColumns(Typed, {{"Make", each Text.Trim(_), type text}, {"Model", each Text.Trim(_), type text}}),
				AddDateKey = Table.AddColumn(Trimmed, "DateKey", each Number.From(Date.ToText(#date([Year], [Month], 1), "yyyyMMdd")), Int64.Type),
				MakeList = List.Distinct(Trimmed[Make]),
				ModelList = List.Distinct(Trimmed[Model]),
				AddMakeKey = Table.AddColumn(AddDateKey, "MakeKey", each List.PositionOf(MakeList, [Make]) + 1, Int64.Type),
				AddModelKey = Table.AddColumn(AddMakeKey, "ModelKey", each List.PositionOf(ModelList, [Model]) + 1, Int64.Type),
				Final = Table.ReorderColumns(AddModelKey, {"DateKey", "Year", "Month", "MakeKey", "ModelKey", "Make", "Model", "Quantity", "Pct"})
			in
				Final
